---
dataset: "sim"
treat: 1  #Id of treatment intervention chosen
n: 1000  # Sample size
T: 15  # Time series length
p: 6  # Covariate dimension influencing treatment
n_cov_cont: 6 #Number of continuous covariates
n_cov_discr: 0 #Number of categorical covariates
burn: 0  # Burn in

noise_X: 0.1
noise_Y: 0.1
noise_A: 0.2

methods:
  - deepace_tar

number_trials: 30
seed: 3843668



